apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
spec:
  ports:
  - name: mysql-master
    port: 3306
  clusterIP: None
  selector:
    app: mysql-master

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
    readonly: "true"
spec:
  ports:
  - name: mysql-slave
    port: 3306
  clusterIP: 10.233.1.20
  selector:
    app: mysql-slave
